// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodo6OulSfe67uQQ2yyd2RZx5dXy7tpnY',
    appId: '1:193431980775:web:a0aeaa4dc4a18aa3047042',
    messagingSenderId: '193431980775',
    projectId: 'quizapp-df17b',
    authDomain: 'quizapp-df17b.firebaseapp.com',
    storageBucket: 'quizapp-df17b.firebasestorage.app',
    measurementId: 'G-19B1T4LX1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu2oXuthgm_gjSpD8AJUDExjquZGLmB_c',
    appId: '1:193431980775:android:4b56a82f4117d2e2047042',
    messagingSenderId: '193431980775',
    projectId: 'quizapp-df17b',
    storageBucket: 'quizapp-df17b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa7kcuuQ1QLJVXSwvDu5viCVQ6o-SWX-Y',
    appId: '1:193431980775:ios:990cb64c7b458d35047042',
    messagingSenderId: '193431980775',
    projectId: 'quizapp-df17b',
    storageBucket: 'quizapp-df17b.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa7kcuuQ1QLJVXSwvDu5viCVQ6o-SWX-Y',
    appId: '1:193431980775:ios:990cb64c7b458d35047042',
    messagingSenderId: '193431980775',
    projectId: 'quizapp-df17b',
    storageBucket: 'quizapp-df17b.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAodo6OulSfe67uQQ2yyd2RZx5dXy7tpnY',
    appId: '1:193431980775:web:31cac0c69be22365047042',
    messagingSenderId: '193431980775',
    projectId: 'quizapp-df17b',
    authDomain: 'quizapp-df17b.firebaseapp.com',
    storageBucket: 'quizapp-df17b.firebasestorage.app',
    measurementId: 'G-D4SJGJT93Y',
  );
}
